### ISSUE TITLE
toe-stubbing

### ISSUE THREAD

**Issue by spaeno** [toxidroma/alchemy-requests#7]
if you walk on a slightly raised surface you have a chance to stub your toe, which makes you fall over in extreme pain

**Comment by spaeno** [comment]
this is serious you should add this

**Comment by amanitasolanaceae** [comment]
not possible because source automatically traverses you vertically atop surfaces that are slightly raised... like stairs
otherwise walking into any kind of wall would be enough for this
that would be simply annoying instead of conditioning players not to do things too unrealistic like running everywhere and into walls
